config/routes.rb
Rails.application.routes.draw do
  get 'time_trackers/index'
  resources :tenants
  resources :appointments

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  constraints subdomain: /.*/ do
  end

  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }


  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "application#redirect"
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
    include MailForm::Delivery
  
    attribute :name,      :validate => true
    attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
    attribute :gender,    :validate => true
    attribute :phone,     :validate => true
    attribute :birthday,  :validate => true
    attribute :address,   :validate => true
    
  
    def headers
      { 
        #this is the subject for the email generated, it can be anything you want
        subject: "New Booking",
        to: 'johndoe111620@gmail.com',
        from: %("Paralejas Notifications") # The <notifications@paralejas.com> is autofill using the email from ENV['GMAIL_EMAIL']
        #the from will display the name entered by the user followed by the email
      }
    end


end

app/controllers/appointments_controller.rb
# frozen_string_literal: true

class AppointmentsController < ApplicationController
  before_action :set_tenant
  before_action :set_appointment, only: %i[show edit update destroy]

  # GET /appointments or /appointments.json
  def index
    @appointments = Appointment.where(tenant_id: @tenant.id)
  end

  # GET /appointments/1 or /appointments/1.json
  def show; end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit; end

  # POST /appointments or /appointments.json
  def create
    birthday = Date.civil(params[:appointment]["birthday(1i)"].to_i,params[:appointment]["birthday(2i)"].to_i,params[:appointment]["birthday(3i)"].to_i)

    year = params[:appointment][:year]
    month = params[:appointment][:month]
    day = params[:appointment][:day]
    hour = params[:appointment]["time(4i)"]
    minute = params[:appointment]["time(5i)"]

    appointment = "#{year}-#{month}-#{day} #{hour}:#{minute}:00"
    @appointment = Appointment.new()
    @appointment.birthday = birthday
    @appointment.appointment = appointment

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1 or /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1 or /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_appointment
    @appointment = Appointment.find_by!(id: params[:id], tenant_id: @tenant.id)
  end

  # Only allow a list of trusted parameters through.
  def appointment_params
    params.require(:appointment).permit(:name, :gender, :phone, :email, :tenant_id, :company_name, :address, :birthday)
  end

  # ...

  def set_tenant
    # @tenant = Tenant.find_by!(id: 1)
    begin
      @tenant = Tenant.find_by!(url: request.subdomain)
    rescue
        #... error handler
    end
    # To access specific tenant, you just need to add the tenant's url before the local host like this: http://tenant1.localhost:3000/
    # Without the request.subdomain on set_tenant, you cannot access the right tenant's url
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<% content_for :head_js do %>
  <%= javascript_packs_with_chunks_tag 'application', 'create_appointment'%>
<% end %>
<%= form_with(model: appointment) do |form| %>
  <% if appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
        <% appointment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="inline-block min-w-half shadow rounded-lg overflow-hidden bg-white mt-5">
<h1 class="mt-4 font-semibold">BOOK AN APPOINTMENT NOW! </h1><br>

  <table class="min-w-full leading-normal">
      <tbody>
          <tr>
              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm"> <p class="text-gray-900 whitespace-no-wrap text-left">Full Name</p> </td>
              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                <%= form.text_field :name, required: true, value: current_user.name, :class => 'bg-white p-1 rounded border-b w-full' %>
              </td>
          </tr>
          <tr>
              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm"> <p class="text-gray-900 whitespace-no-wrap text-left">Email</p> </td>
              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                <%= form.text_field :email, required: true, value: current_user.email, :class => 'bg-white p-1 rounded border-b w-full' %>
              </td>
          </tr>
          <tr>
              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm"> <p class="text-gray-900 whitespace-no-wrap text-left">Phone Number</p> </td>
              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                <%= form.text_field :phone, required: true, :class => 'bg-white p-2 rounded border-b w-full', :placeholder => '+639xxxxxxxxxx' %>
              </td>
          </tr>
          <tr>
              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm"> <p class="text-gray-900 whitespace-no-wrap text-left">Gender</p> </td>
              <td class="border-b border-gray-200 bg-white text-sm text-left pl-5">
                <%= form.label :gender, "Male", :value => "male"  %>
                <%= form.radio_button :gender, 'male' %>
                <%= form.label :gender, "Female", :value => "female" %>
                <%= form.radio_button :gender, 'female'%>
                <%= form.label :gender, "N/A", :value => "none" %>
                <%= form.radio_button :gender, 'none', :checked => true %>
              </td>
          </tr>
          <tr>
              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm"> <p class="text-gray-900 whitespace-no-wrap text-left">Birthday</p> </td>
              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm text-left pl-5">
                <%= form.date_select :birthday,{:start_year => Date.today.year, :end_year => 1960}, {class: "form-select appearance-none px-3 py-1.5  font-normal text-gray-700 bg-white bg-clip-padding bg-no-repeat border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"}  %>
              </td>
          </tr>
          <tr>
              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm"> <p class="text-gray-900 whitespace-no-wrap text-left">Address</p> </td>
              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                <%= form.text_field :address, :placeholder => 'Street, Barangay', required: true, :class => 'bg-white p-1 rounded border-b w-full' %>
                <br>
                <%= form.text_field :address, :placeholder => 'Municipality/ City', required: true, :class => 'bg-white p-1 rounded border-b w-full' %>
              </td>
          </tr>
          <tr>
              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm"> <p class="text-gray-900 whitespace-no-wrap text-left">Date & Time</p> </td>
              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm text-left pl-5">
                <%= form.select :year, (Date.today.year..Date.today.year+2).collect { |y| y }, options = {}, id: "", :class => "form-select appearance-none px-3 py-1.5  font-normal text-gray-700 bg-white bg-clip-padding bg-no-repeat border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" %>

                <%= form.select :month, options_for_select(%w[January February March April May June July August September October November December]), {}, { :class => 'month_select form-select appearance-none px-3 py-1.5  font-normal text-gray-700 bg-white bg-clip-padding bg-no-repeat border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none'} %>
                <%= form.select :day, options_for_select(%w[1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31]), {}, { :class => 'day_select form-select appearance-none px-3 py-1.5  font-normal text-gray-700 bg-white bg-clip-padding bg-no-repeat border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none' } %>

                <%= form.time_select :time, {:ignore_date => true, :minute_step => 30, :ampm => true }, { :class => "form-select appearance-none px-3 py-1.5  font-normal text-gray-700 bg-white bg-clip-padding bg-no-repeat border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" }  %>
              </td>
          </tr>
      </tbody>
  </table>

  <div class="actions bg-white">
      <div id="appointment_dates"><% Appointment.all.each do |row| %><%= row.appointment %>,<% end %></div>

      <div class="field">
        <%= form.hidden_field :tenant_id, value: @tenant.id %>
        <%= form.hidden_field :company_name, value: @tenant.company_name %>
        <label for="for_cloning_select"></label>
        <select class="d-none" name="" id="for_cloning_select" style="display:none">

        </select>
      </div>

      <div class="actions">
        <br><%= form.submit 'Create Appointment', :class => 'bg-purple-700 text-white active:bg-purple-800 font-bold uppercase text-sm px-6 py-3 rounded shadow hover:shadow-lg outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150 cursor-pointer' %><br><br>
      </div>
  </div>
</div>
<% end %>

app/views/appointments/_form2.html.erb
<% content_for :head_js do %>
  <%= javascript_packs_with_chunks_tag 'create_appointment'%>
<% end %>

<%= form_with(model: appointment) do |form| %>
  <% if appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
        <% appointment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>Set New Date and Time</p>
    <%= form.label :name %>
    <%= form.text_field :name %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email,:readonly => true %>
  </div>

  <div class="field">
    <br>
    <p>Should be <b><i>'Date & Time and Optional Message field'</i></b> (Is there anything you want to tell the Client?) </p>
  </div>

  <div class="field">
  <%= form.hidden_field :tenant_id, value: @tenant.id %>
  </div>

<br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<% content_for :title do %>Edit Appointment<% end %>
    
<% if current_user.superadmin_role == TRUE ||  current_user.supervisor_role == TRUE %>
    
    <h1>Editing Appointment</h1>
    <br>
        
    <%= render 'form2', appointment: @appointment %>
    
<% else %>
    
      <%= link_to 'Book an appointment to ' + @tenant.company_name , new_appointment_path %>
    
<% end %>

app/views/appointments/index.html.erb
<% content_for :title do %><%= @tenant.company_name %><% end %>
<br>
<% if current_user.superadmin_role == TRUE || current_user.supervisor_role == TRUE || current_user.email == @tenant.email %>

  <div class="container mx-auto px-4 sm:px-8">
      <div class="py-8">
          <div>
              <h2 class="text-2xl font-semibold leading-tight">Appointment List</h2>
          </div>
          <div class="-mx-4 sm:-mx-8 px-4 sm:px-8 py-4 overflow-x-auto">
              <div class="inline-block min-w-full shadow rounded-lg overflow-hidden">
                  <table class="min-w-full leading-normal">
                      <thead>
                          <tr>
                              <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-center text-xs font-semibold text-gray-600 uppercase tracking-wider">Name</th>
                              <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-center text-xs font-semibold text-gray-600 uppercase tracking-wider">Gender</th>
                              <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-center text-xs font-semibold text-gray-600 uppercase tracking-wider">Phone</th>
                              <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-center text-xs font-semibold text-gray-600 uppercase tracking-wider">Birthday</th>
                              <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-center text-xs font-semibold text-gray-600 uppercase tracking-wider">Address</th>
                              <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-center text-xs font-semibold text-gray-600 uppercase tracking-wider">Email</th>
                              <th colspan="3" class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-center text-xs font-semibold text-gray-600 uppercase tracking-wider"></th>
                          </tr>
                      </thead>
                      <tbody>
                        <% @appointments.each do |appointment| %>
                        
                          <tr>
                              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                                <p class="text-gray-900 whitespace-no-wrap text-center"><%= appointment.name %></p>
                              </td>

                              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                                  <p class="text-gray-900 whitespace-no-wrap text-center"><%= appointment.gender %></p>
                              </td>

                              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                                  <p class="text-gray-900 whitespace-no-wrap text-center"><%= appointment.phone %></p>
                              </td>

                              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                                  <p class="text-gray-900 whitespace-no-wrap text-center"><%= appointment.birthday %></p>
                              </td>

                              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                                  <p class="text-gray-900 whitespace-no-wrap text-center"><%= appointment.address %></p>
                              </td>

                              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                                <p class="text-gray-900 whitespace-no-wrap text-center"><%= appointment.email %></p>
                              </td>

                              <td class="py-5 border-b border-gray-200 bg-white text-sm">
                                <%= link_to 'Show', appointment, class:"bg-yellow-500 hover:bg-yellow-700 text-white font-bold py-2 px-4 rounded" %>
                              </td>

                              <td class="py-5 border-b border-gray-200 bg-white text-sm">
                                <%= link_to 'Edit', edit_appointment_path(appointment), class:"bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded" %>
                              </td>

                              <td class="py-5 border-b border-gray-200 bg-white text-sm">
                                <%= link_to 'Cancel Booking', appointment, method: :delete, class:"bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded", data: { confirm: 'Are you sure?' } %>
                              </td>

                          </tr>
                          <% end %>
                      </tbody>
                  </table>
              </div>
          </div>
      </div>
  </div>
  
<% else %>
  
  <% if @tenant.url == "admin" %>
  
    <h1>Welcome to Paralejas Consulting</h1><br>
    <h1>Go to the correct url of the Company</h1>
    
  <% else %>
  
    <h1>Go to the correct url of the Company</h1>
    <br>
    <%= link_to 'Book an appointment to ' + @tenant.company_name , new_appointment_path %>
  
  <% end %>
<% end %>

app/views/appointments/new.html.erb
<% content_for :title do %>Book Now!<% end %>

<% if @tenant %>

  <% if !@tenant.url == "admin" %>

    <h1>Go to the correct url of the Company</h1>

  <% else %>

    <!-- <h1><%= @tenant.company_name %> page</h1><br> -->
    <%= render 'form', appointment: @appointment %>

  <% end %>

<% else %>
  <h1>Go to the correct url of the Company</h1>
<% end %>

app/views/appointments/show.html.erb
<% content_for :title do %><%= @tenant.company_name %><% end %>

<% if current_user.superadmin_role == TRUE ||  current_user.supervisor_role == TRUE %>

  <div class="container mx-auto px-4 sm:px-8">
      <div class="py-8">
          <div class="-mx-4 sm:-mx-8 px-4 sm:px-8 py-4 overflow-x-auto">
              <div class="inline-block min-w-half shadow rounded-lg overflow-hidden">
                <div class="flex bg-gray-100">
                  <div class="flex-none">
                    <h2 class="text-2xl font-semibold leading-tight p-3">Appointment Details</h2>
                  </div>
                  <div class="flex-1"></div>
                </div>

                  <table class="min-w-full leading-normal">
                      <tbody>
                          <tr>
                              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm"> <p class="text-gray-900 whitespace-no-wrap text-left">Name</p> </td>
                              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm"> <p class="text-gray-900 whitespace-no-wrap text-right"><%= @appointment.name %></p> </td>
                          </tr>
                          <tr>
                              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm"> <p class="text-gray-900 whitespace-no-wrap text-left">Gender</p> </td>
                              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm"> <p class="text-gray-900 whitespace-no-wrap text-right"><%= @appointment.gender %></p> </td>
                          </tr>
                          <tr>
                              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm"> <p class="text-gray-900 whitespace-no-wrap text-left">Phone</p> </td>
                              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm"> <p class="text-gray-900 whitespace-no-wrap text-right"><%= @appointment.phone %></p> </td>
                          </tr>
                          <tr>
                              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm"> <p class="text-gray-900 whitespace-no-wrap text-left">Birthday</p> </td>
                              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm"> <p class="text-gray-900 whitespace-no-wrap text-right"><%= @appointment.birthday %></p> </td>
                          </tr>
                          <tr>
                              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm"> <p class="text-gray-900 whitespace-no-wrap text-left">Appointment Date & Time</p> </td>
                              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm"> <p class="text-gray-900 whitespace-no-wrap text-right"><%= @appointment.appointment %></p> </td>
                          </tr>
                          <tr>
                              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm"> <p class="text-gray-900 whitespace-no-wrap text-left">Address</p> </td>
                              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm"> <p class="text-gray-900 whitespace-no-wrap text-right"><%= @appointment.address %></p> </td>
                          </tr>
                          <tr>
                              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm"> <p class="text-gray-900 whitespace-no-wrap text-left">Email</p> </td>
                              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm"> <p class="text-gray-900 whitespace-no-wrap text-right"><%= @appointment.email %></p> </td>
                          </tr>
                      </tbody>
                  </table>

                  <%= link_to 'Back', appointments_path %> |
                  <%= link_to 'Reschedule', edit_appointment_path(@appointment) %> |
                  <%= link_to 'Cancel Booking', @appointment, method: :delete, data: { confirm: 'Are you sure?' } %>

              </div>
          </div>
      </div>
  </div>



<% else %>

  <div class="container mx-auto px-4 sm:px-8">
      <div class="py-8">
          <div class="-mx-4 sm:-mx-8 px-4 sm:px-8 py-4 overflow-x-auto">
              <div class="inline-block min-w-half shadow rounded-lg overflow-hidden">
                <div class="flex bg-gray-100">
                  <div class="flex-none">
                    <h2 class="text-2xl font-semibold leading-tight p-3">Appointment Details</h2>
                  </div>
                  <div class="flex-1"></div>
                </div>

                  <table class="min-w-full leading-normal">
                      <tbody>
                          <tr>
                              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm"> <p class="text-gray-900 whitespace-no-wrap text-left">Name</p> </td>
                              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm"> <p class="text-gray-900 whitespace-no-wrap text-right"><%= @appointment.name %></p> </td>
                          </tr>
                          <tr>
                              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm"> <p class="text-gray-900 whitespace-no-wrap text-left">Gender</p> </td>
                              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm"> <p class="text-gray-900 whitespace-no-wrap text-right"><%= @appointment.gender %></p> </td>
                          </tr>
                          <tr>
                              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm"> <p class="text-gray-900 whitespace-no-wrap text-left">Phone</p> </td>
                              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm"> <p class="text-gray-900 whitespace-no-wrap text-right"><%= @appointment.phone %></p> </td>
                          </tr>
                          <tr>
                              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm"> <p class="text-gray-900 whitespace-no-wrap text-left">Birthday</p> </td>
                              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm"> <p class="text-gray-900 whitespace-no-wrap text-right"><%= @appointment.birthday %></p> </td>
                          </tr>
                          <tr>
                              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm"> <p class="text-gray-900 whitespace-no-wrap text-left">Appointment Date & Time</p> </td>
                              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm"> <p class="text-gray-900 whitespace-no-wrap text-right"><%= @appointment.appointment %></p> </td>
                          </tr>
                          <tr>
                              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm"> <p class="text-gray-900 whitespace-no-wrap text-left">Address</p> </td>
                              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm"> <p class="text-gray-900 whitespace-no-wrap text-right"><%= @appointment.address %></p> </td>
                          </tr>
                          <tr>
                              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm"> <p class="text-gray-900 whitespace-no-wrap text-left">Email</p> </td>
                              <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm"> <p class="text-gray-900 whitespace-no-wrap text-right"><%= @appointment.email %></p> </td>
                          </tr>
                      </tbody>
                  </table>
              </div>
          </div>
          <%= link_to 'Book Another', new_appointment_path, class:"bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded" %>
      </div>
  </div>
<% end %>