config/routes.rb
Rails.application.routes.draw do
  get 'time_trackers/index'
  resources :tenants
  resources :appointments

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  constraints subdomain: /.*/ do
  end

  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }


  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "application#redirect"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= yield(:title) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css">
    <%= stylesheet_link_tag "authentication"%>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'custom', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'custom', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://code.jquery.com/jquery-3.6.0.min.js" %>
    <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js" %>
    <%= javascript_include_tag "https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" %>
    <%= yield(:head_js) %>
  </head>

<body class="bg-gray-200">

<nav class="bg-gray-800">
  <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
    <div class="relative flex items-center justify-between h-16">
      <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
        <!-- Mobile menu button-->
        <button type="button" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white" aria-controls="mobile-menu" aria-expanded="false">
          <span class="sr-only">Open main menu</span>
          <svg class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
          </svg>
          <svg class="hidden h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div class="flex-1 flex items-center justify-center sm:items-stretch sm:justify-start">
        <div class="flex-shrink-0 flex items-center">
          <!-- <img class="block lg:hidden h-8 w-auto" src="https://tailwindui.com/img/logos/workflow-mark-indigo-500.svg" alt="Workflow"> -->

          <% if user_signed_in? %>
            <% if current_user.superadmin_role %>
            <a href="<%= new_appointment_path %>" class="font-black text-white w-auto">Admin</a>
            <% elsif current_user.supervisor_role %>
            <a href="<%= new_appointment_path %>" class="font-black text-white w-auto"><%= @tenant.company_name %></a>
            <% else %>
            <a href="<%= new_appointment_path %>" class="font-black text-white w-auto">Octo Sched</a>
            <% end %>
          <% else %>
            <a href="<%= new_appointment_path %>" class="font-black text-white w-auto">Octo Sched</a>
          <% end %>

        </div>
        <div class="hidden sm:block sm:ml-6">
          <div class="flex space-x-4">
            <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
            <!--  bg-gray-900 text-white px-3 py-2 rounded-md text-sm font-medium  -->

            <% if user_signed_in? %>
              <% if current_user.superadmin_role %>
                <%= link_to "Admin Dashboard", rails_admin_path, class:'text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium', target: :_blank %>
                <%= link_to "Manage Tenants", tenants_path, class:'text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium' %>
                <%= link_to 'Create Tenant', new_tenant_path, class:'text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium' %>
                <% elsif current_user.supervisor_role %>
                <%= link_to "Manage Appointments", appointments_path, class:'text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium' %>
                <%= link_to 'Edit Company', edit_tenant_path(@tenant), class:"text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
              <% end %>
            <% end %>

          </div>
        </div>
      </div>

      <% if user_signed_in? %>
        <div class="ml-3 relative">
           <div x-data="{ dropdownOpen: false }" class="relative my-32">
              <button @click="dropdownOpen = !dropdownOpen" class="bg-gray-800 p-1 rounded-full text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white">
              <span class="sr-only">Open user menu</span>
              <%= image_tag 'user.svg', alt: "user image",class: "p-1 h-8 w-8 rounded-full" %>
              </button>
              <div x-show="dropdownOpen" @click="dropdownOpen = false" class="fixed inset-0 h-full w-full z-10" style="display: none;"></div>
              <div x-show="dropdownOpen" class="absolute w-64 right-0 mt-2 bg-white rounded-md shadow-lg overflow-hidden z-20" style="display: none;">
                 <div class="py-2">
                   <%= link_to "User Profile", edit_user_registration_path, class:"flex block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100", 'role':"menuitem", method: :get %>
                   <%= link_to "Logout", destroy_user_session_path, class:"flex block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100", 'role':"menuitem", method: :delete %>
                 </div>
              </div>
           </div>
        </div>
      <% end %>

      </div>
    </div>

  <!-- Mobile menu, show/hide based on menu state. -->
  <div class="sm:hidden" id="mobile-menu">
    <div class="px-2 pt-2 pb-3 space-y-1">
      <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
      <a href="#" class="bg-gray-900 text-white block px-3 py-2 rounded-md text-base font-medium" aria-current="page">Dashboard</a>

      <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium">Team</a>

      <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium">Projects</a>

      <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium">Calendar</a>
    </div>
  </div>
</nav>

<div class="container mx-auto px-4 sm:px-8">
    <div class="py-8">

      <%
      if user_signed_in?
        unless session[:display_welcome]
          flash.now[:notice] = "Welcome! " + current_user.name
          session[:display_welcome] = true
        end
      end
      %>


      <% if notice %>
        <div class="text-center alert-login alert_default alert-dismissible">
          <a href="#" class="flash_close_btn" data-dismiss="alert" aria-label="close">&times;</a>
          <%= notice %>
        </div> <br>
      <% end %>

    <%= yield %>

  </div>
</div>

</body>
</html>

app/views/layouts/main.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Time Tracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>